spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://reminder.cnvahiynenth.ap-northeast-2.rds.amazonaws.com:3306/rdsreminder
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: chos
    password: alsrl9913

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true

logging:
  level:
    com.tutorial: debug

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
